  - name: Change BIG-IP admin password
    bigip_command:
      provider:
        server: "{{item.value.public_ip}}"
        ssh_keyfile: "~/.ssh/{{item.value.sshkey}}"
        transport: cli
        user: admin
      commands: modify auth user admin password {{bigip_password}}
      warn: no
    delegate_to: localhost
    with_dict: 
      - "{{aws}}"

