
  - name: Add new user **ansible** to BIG-IP for use in the playbook
    bigip_command:
      provider:
        server: "{{item.value.public_ip}}"
        ssh_keyfile: "~/.ssh/{{item.value.sshkey}}"
        transport: cli
        user: admin
        timeout: 60
      commands: create auth user {{bigip_username}} { password {{bigip_password}} partition-access add { all-partitions { role admin } } shell bash }
      warn: no
    delegate_to: localhost
    with_dict: 
      - "{{aws}}"
