  - name: Show public IP's and password to check your work
    debug: 
      msg:
        #- "Ansible password is {{bigip_password}}"
        - "{{item.value.region}} Public IP address: {{item.value.public_ip}}"
        - ""
    with_dict:
      - "{{aws}}"
