---  
- name: Task to destroy environment using Terraform
  
  hosts: 127.0.0.1
  gather_facts: no
  vars:
    aws:
      us_east_1:
        region: us-east-1
        sshkey: leonardo_f5_aws.pem
        public_ip:
      us_east_2:
        region: us-east-2
        sshkey: f5_aws_acct_keypair.pem
        public_ip: 
      us_west_2:
        region: us-west-2
        sshkey: leonardo_oregon_aws.pem
        public_ip:
      ap_southeast_1:
        region: ap-southeast-1
        sshkey: leonardo_singapore_aws.pem
        public_ip: 
      eu_west_2:
        region: eu-west-2
        sshkey: leonardo_london_aws.pem
        public_ip: 
    aws_public_ips: {}
    generic_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
    debug_on: true

  tasks:

  - name: Task to destroy environment using Terraform
    import_tasks: tasks/terraformDestroy.yml
    

