---  

- name: Initial GSLB cluster build; create, base configuration, cluster configs, ready for production traffic
  hosts: 127.0.0.1

  vars: 
    aws_east_1: 
      region_name: us-east-1
      region_key: leonardo_f5_aws.pem
    aws_east_2: 
      region_name: us-east-2
      region_key: f5_aws_acct_keypair.pem
    aws_west_2: 
      region_name: us-west-2
      region_key: leonardo_oregon_aws.pem
    project_dir: ../terraform/prod/{{aws_west_2.region_name}}
    ssh_keyfile: "~/.ssh/{{aws_west_2.region_key}}"
    bigip_password: (password)
   
  tasks:
  - name: initiating task_terraformDeploy
    import_tasks: tasks/terraformDeploy.yml
  - name: initiating task_wait4bigip
    import_tasks: tasks/wait4bigip.yml
  - name: initiating task_changeAdminPass
    import_tasks: tasks/changeAdminPass.yml
  - name: initiating task_wait4REST.yml
    import_tasks: tasks/wait4REST.yml

  #- import_tasks: 
  #- import_tasks: task_changeAdminPass.yml
  #- import_tasks: task_wait4REST.yml
  


